language: php

php:
  - "7.3"

services:
  - docker

install:
  - npm install
  - docker-compose up -d && sleep 10

script:
  - npm run lint
  - npm run docker -- npm run test:php:coverage

after_success:
  - npm run docker -- npm run coverage:merge:php
  - docker-compose run -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN --workdir=/var/www/html/wp-content/plugins/unsplash-wp wordpress -- composer coverage

notifications:
  email: false

# Pull requests are built by default.
branches:
  only:
  - master

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
