language: php

php:
  - "7.3"

services:
  - docker

install:
  - npm install
  - docker-compose up -d
  - sleep 10

script:
  - npm run lint
  - npm run docker -- npm run test:php:coverage

after_success:
  - npm run coverage:merge:php
  - sleep 5
  - npm run coverage:php

notifications:
  email: false

# Pull requests are built by default.
branches:
  only:
  - master

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
