language: php

php:
  - "7.3"

services:
  - docker

install:
  - npm install

script:
  - npm run lint
  - npm run docker -- npm run test:php:coverage:unit

after_success:
  - npm run coverage

notifications:
  email: false

# Pull requests are built by default.
branches:
  only:
  - master

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
